### ISSUE TITLE
Match function not working

### ISSUE THREAD

**Issue by Gallen1124** [capella-ben/microPython_MCP2515#2]
Hi, 

I need some help working your code. I need to isolate messages from a specific CAN_ID. I am using 11bit identifiers. 

In this section of code I see that you can have an argument that you can put a list of IDs into. I have set my NODE_ID = 0x141. This works correctly as I can send a CAN message on that ID fine. However when I try to use it to create a match in the argument for listening it gave me an error. 

with can_bus.listen(matches=[NODE_ID] ,timeout=1.0) as listener:

Unfortunately, since then I reloaded the code and now if I run your code downloaded directly to my raspberry pi pico it just gives me this error.

MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "MCP2515.py", line 219, in __init__
  File "MCP2515.py", line 251, in initialize
  File "MCP2515.py", line 551, in _set_mode
  File "MCP2515.py", line 570, in _request_new_mode
RuntimeError: Timeout setting Mode

**Comment by v-forman** [comment]
Hi,

same problem for me, I cannot get the "matches" parameter to work. My code is as follow:
NODE_ID = 0x1234ABCD
with can_bus.listen(matches=[NODE_ID] ,timeout=1.0) as listener:

I get the following error:
File "MCP2515.py", line 668 in _crate_mask
AttributeError: 'int' object has no attribute 'mask'

The implementation in MCP2515.py states: "A message can be received by at most one Listener. If more than one listener matches a message, it is undefined which one actually receives it."

If I understand correctly, message filtering has to be setup when calling CAN.listen to ensure that a particular device will only receive the messages it is supposed to and not prevent other devices to get them. Since my project involves multiple devices awaiting messages, I need to be able to filter by ID...

Any help would be greatly appreciated!

**Comment by v-forman** [comment]
I think I figured it out. Here is my code:

```
from collections import namedtuple

NODE_ID = 0x123
Match = namedtuple('Match', ['mask', 'address', 'extended'])
m = Match(0xFFFFFFFF, NODE_ID, False)

can_bus = CAN(0, 17, baudrate = 25000, debug=False)
i = 0
while True:
    with can_bus.listen(matches=[m],timeout=1.0) as listener:
        #etc.
```
